spring.application.name=PrepIntel

# PostgreSQL Connection Settings
spring.datasource.url=jdbc:postgresql://localhost:5432/prepintel
spring.datasource.username=postgres
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA and Hibernate configuration
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

# Database Initialization
spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema.sql

# Server Port
server.port=8080

# Import local secrets (this file is gitignored)
spring.config.import=optional:classpath:application-secret.properties
